//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSCTraining_German3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Subject
    {
        public int ID { get; set; }
        public int SubjectID { get; set; }
        public int StudentID { get; set; }
        public string Grade { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
